name: AdvancedMining
version: '1.2'
main: com.eero.advancedmining.AdvancedMining
api-version: '1.21'
authors: [ CodingBoulder ]
description: A plugin that adds a custom mining system
website: https://hangar.papermc.io/CodingBoulder/AdvancedMining
